name: Release Native

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: RcloneWebuiAngular-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            RcloneWebuiAngular-${{ runner.os }}-node-

      - name: Build
        run: |
          npm clean-install
          npm run build:native

      - name: Archive as Zip
        run: |
          cp src/i18n-index.html dist/build/index.html
          cd dist
          zip -r native.zip build
          mkdir -p release/${{ github.ref_name }}
          mv native.zip release/${{ github.ref_name }}/native.zip
